### ISSUE TITLE
client.QueryPlayer() may be broken due to a2s change.

### ISSUE THREAD

**Issue by RootInit** [rumblefrog/go-a2s#12]
I just checked in one of my services that apparently died months ago. It queried Unturned servers and fetched a player list. Apparently the service down email never got sent because it has been down for months. I don't care to look into it and am only making this issue to warn people who may be going to use this library in the future since no updates have been made since.

The error I get is only: `read udp MY-IP:39138->SERVER-IP:6144: i/o timeout`

**Comment by rumblefrog** [comment]
Network unreachable is not a problem of the library, I recommend checking via netcat for connectivity. This library follows Source's [A2S](https://developer.valvesoftware.com/wiki/Server_queries) protocol, which has not changed in eons, not sure what update to this library you would expect?

**Comment by RootInit** [comment]
> Network unreachable is not a problem of the library, I recommend checking via netcat for connectivity. This library follows Source's [A2S](https://developer.valvesoftware.com/wiki/Server_queries) protocol, which has not changed in eons, not sure what update to this library you would expect?

Appologies. It turned out to be that the servers I monitored blocked external a2s queries. I tested a different server with a python a2s library for convenience which worked and I reached flawed conclusions as it had been updated reciently.

Sorry again.
