### ISSUE TITLE
New server query protocol

### ISSUE THREAD

**Issue by f8192** [rumblefrog/go-a2s#4]
A2S_INFO may now respond with a challenge request. A quote from here https://developer.valvesoftware.com/wiki/Server_queries :

> Servers may respond with the data immediately. However, since this reply is larger than the request, it makes the server vulnerable to a reflection amplification attack. Instead, the server may reply with a challenge to the client using S2C_CHALLENGE ('A' or 0x41). In that case, the client should repeat the request by appending the challenge number. This change was introduced in December 2020 to address the reflection attack vulnerability, and all clients are encouraged to support the new protocol.

Please add support

**Comment by mpawlowski** [comment]
I ran into this issue today. I think I fixed it with https://github.com/rumblefrog/go-a2s/pull/5.
